language: node_js
sudo: true
dist: trusty

node_js:
  - "node"

matrix:
  include:
    # Code linting
    - script:
        - npm run format:check

    # Test Build
    - script:
        - npm run build

    # Node.js Tests
    - script:
        - npm test

    # Coverage Report
    - script:
        - npm run build:test
        - $(npm bin)/nyc report --reporter=text-lcov | $(npm bin)/coveralls

    # Browser tests
    - addons:
        chrome: stable
        firefox: latest
      before_script:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
      script:
        - npm run test:browser

cache:
  directories:
    - "node_modules"
