language: node_js

node_js:
  - "node"

script:
  - npm run format:check --verbose # style check
  - npm run build # build
  - npm run test # node test
  - npm run test:browser # browser test
#  - npm run test:coverage # generate coverage report
#  - $(npm bin)/nyc report --reporter=text-lcov | $(npm bin)/coveralls # report coverage to coveralls

cache:
  directories:
    - "node_modules"