language: node_js
sudo: true
dist: trusty

node_js:
  - "node"

addons:
  chrome: stable
  firefox: latest

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run format:check --verbose # style check
  - npm run build # build
  - npm run test # node test
  - npm run test:browser # browser test
#  - npm run test:coverage # generate coverage report
#  - $(npm bin)/nyc report --reporter=text-lcov | $(npm bin)/coveralls # report coverage to coveralls

cache:
  directories:
    - "node_modules"
