language: node_js

node_js:
  - "node"

script:
  - npm run format:check --verbose # style check
  - npm run coverage # run test cases and and generate coverage report
  - $(npm bin)/nyc report --reporter=text-lcov | $(npm bin)/coveralls # report coverage to coveralls

cache:
  directories:
    - "node_modules"